### ISSUE TITLE
Issue on Toggle

### ISSUE THREAD

**Issue by TTP1106** [creativetimofficial/black-dashboard#11]
I am getting an Issue on Toggle-Button. Toggle on resize is working fine. Toggle on button without any function:

[html.txt](https://github.com/creativetimofficial/black-dashboard/files/2543848/html.txt)

**Comment by rarestoma** [comment]
Hi,

Thank you for the interest in our products. Please modify the roots for the css files (it need to be ../assets/... not assets/...) and also please add the bootstrap css:
     <link href="../assets/css/bootstrap.min.css" rel="stylesheet" />

Please let me know if everyting is good and if i can help you with anything else.

All the best,
Rares
