### ISSUE TITLE
tablesorter gif missing

### ISSUE THREAD

**Issue by ndousson** [creativetimofficial/black-dashboard#12]
Hi,

I downloaded your template to use it with webpack.

At my first build, i had errors for some missing files :

> ModuleNotFoundError: Module not found: Error: Can't resolve '../img/asc.gif' in ...

Next, i have looked at your css file and i found this three references to X.gif who are not present in the release :

`background-image: url("../img/bg.gif");` line 14345
`background-image: url("../img/asc.gif");` line 14352
`background-image: url("../img/desc.gif");` line 14356

I commented this lines in my code.

I had this error too :

> ModuleNotFoundError: Module not found: Error: Can't resolve '../fonts/nucleo.svg' in ...

This error come from nucleo-icons.css at line 12 :

`url('../fonts/nucleo.svg') format('svg')`

I commented it too.

I think it was just some files who was not versionned.

Have a nice day.

**Comment by rarestoma** [comment]
Hello,

Thank you for the interest in our products.

Yes, we have to remove these lines in our next update because we do not use such elements in this theme.

All the best,
Rares

**Comment by ndousson** [comment]
Hi @rarestoma,

Thank you for your answer.

I let you close this issue or maybe let it open but with **Milestone** next update or **Labels** evolution ;)

Nicolas.

**Comment by IceBreakerG** [comment]
Just an update, but this was not fixed in version 1.0.1.

**Comment by filliph** [comment]
It's still an issue. This is the SCSS when installing via `npm`:

```
table.tablesorter thead tr .header{
	background-image: url("../../../assets/img/dashboard/pro/bg.gif");
  background-repeat: no-repeat;
  background-position: center right;
  cursor: pointer;
}

table.tablesorter thead tr .headerSortUp {
	background-image: url("../../../assets/img/dashboard/pro/asc.gif");
}
table.tablesorter thead tr .headerSortDown {
	background-image: url("../../../assets/img/dashboard/pro/desc.gif");
}
```

If the free version doesn't work, how is anyone meant to have confidence the paid version works?

**Comment by rarestoma** [comment]
Hello,

Thank you for your interest in our product. We will change these lines in our next updates but until then please remove them. The PRO version contains the DataTable.net component that has the order option. Please check the PRO version here: https://themes.getbootstrap.com/product/black-dashboard-pro-premium-bootstrap-4-admin/.

I hope it helps.

All the best, 
Rares

**Comment by vip3rousmango** [comment]
This is still occurring...
Just hit this when trying to build using Parcel 1 or 2.

```bash
× Build failed.
@parcel/resolver-default: Cannot find module '../img/asc.gif' from 'R:\NG-VS-Dashboard\assets\css'
R:\NG-VS-Dashboard\assets\css\black-dashboard.css
R:\NG-VS-Dashboard\assets\css\black-dashboard.css:11553:3
  11552 | table.tablesorter thead tr .headerSortUp {
> 11553 |   background-image: url("../img/asc.gif"); }
>       |   ^^^^^^^^^^^^^^^^
  11554 |
  11555 | table.tablesorter thead tr .headerSortDown {
```

**Comment by rarestoma** [comment]
Hi @vip3rousmango,

Thank you for working with our products.

It is in our next update list. I hope we will launch the new update as soon as possible.

Thank you,
Rares
