### ISSUE TITLE
Sidebar-mini on RTL version has extra padding

### ISSUE THREAD

**Issue by hadifar** [creativetimofficial/black-dashboard#14]
There is some extra padding in RTL version which cause content not align with sidebar. 

<img width="468" alt="screen shot 1397-11-24 at 17 18 45" src="https://user-images.githubusercontent.com/7101287/52716267-a7a87f80-2fb3-11e9-9ec9-0e943a77dfe5.png">

**Comment by rarestoma** [comment]
Hello,

Thank you for the interest in our products.

Please update the css file with this change:

.rtl .main-panel .content {
    padding: 80px 300px 20px 50px;
}

Please let me know if I can help you with anything else.

All the best,
Rares

**Comment by hadifar** [comment]
Thanks for your reply. It fixed.
