### ISSUE TITLE
toggle bar icon is fixed in RTL version

### ISSUE THREAD

**Issue by hadifar** [creativetimofficial/black-dashboard#15]
Hi again, it seems toggle icon in RTL version is not moving as expected. When scrolling down its position fixed there.

<img width="666" alt="screen shot 1397-11-29 at 22 11 56" src="https://user-images.githubusercontent.com/7101287/52970835-89cf8600-33ca-11e9-82f7-83de8257e60e.png">

**Comment by rarestoma** [comment]
Hi,

Thank you for the interest in our products and sorry for the late response.

Please remove from the css all the attributes for the .rtl .main-panel and the everything will work fine.

All the best,
Rares
