### ISSUE TITLE
input type file has design issue

### ISSUE THREAD

**Issue by ihrifat2** [creativetimofficial/black-dashboard#16]
Hi team,

I facing an issue, the input type file it shows nothing but when I click in the image or in Additional Image from the browser the file manager comes up.

![image](https://user-images.githubusercontent.com/25511354/59526162-14983b80-8efa-11e9-8a90-e851319081ce.png)

Thanks

**Comment by rarestoma** [comment]
Hi,

Thank you for working with our products.

Can you please give me a jsfiddle link with the issue so I can see exactly what happens?

All the best,
Rares

**Comment by ihrifat2** [comment]
Hey @rarestoma 

Thank you for your reply. 

You can find the jsfiddle link in here: https://jsfiddle.net/g2omh3q9/1/

I think if the input type file looks like the below photo then it would be much understandable in dark theme. I hope you understand. let me know if I miss anything. 
![image](https://user-images.githubusercontent.com/25511354/59916265-8283bc00-9440-11e9-84aa-e4f39406869e.png)

Cheers

**Comment by rarestoma** [comment]
Hi,

We provide a file input in our pro version of Black Dashboard available on the official bootstrap website(https://themes.getbootstrap.com/product/black-dashboard-pro-premium-bootstrap-4-admin/).

You can preview it on the Forms->Extended Forms page.

All the best,
Rares
