### ISSUE TITLE
Datatables 1.10.19 and scroller extension 2.0.0

### ISSUE THREAD

**Issue by ghost** [creativetimofficial/black-dashboard#17]
Hi,

We use black-dashboard.css in our webapplication, and the application uses datatables version 1.10.19 and the datatables scroller extension, version 2.0.0 - and the whole site builds upon bootstrap 4. 

We've experienced that the Edge browser (Microsoft Edge 44.17763.1.0) has problems with the datatables scroller extension, and only when the black-dashboard sheet is used. 

If we bypass the black-dashboard sheet, datatables with the scroller works fine. Chrome and Firefox has no problem rendering the content nicely.

Inspecting the black-dashboard sheet indicates that is was built with datatables-1.10.18 and datatables scroller 1.5.0. 

Could we try to have an updated version built on recent versions?

Here's an image of the resulting problem in Edge - there's a sort of loading indicator all over, and the contents are present, but hardly visible. And it renders without vertical scrollbar which is also not an issue in Chrome/Firefox.

![image](https://user-images.githubusercontent.com/37500345/59961528-536d5900-94d9-11e9-9c28-41491172ed79.png)

Here is how it looks in Chrome...

![image](https://user-images.githubusercontent.com/37500345/59961540-6f70fa80-94d9-11e9-9054-8ab287845c06.png)

Thank you for your support on this.. and an otherwise awesome theme.

mlgdk

**Comment by rarestoma** [comment]
Hi,

Thank you for working with our products.

We provide Data Table in our Pro Version available on the official Bootstrap Marketplace (https://themes.getbootstrap.com/product/black-dashboard-pro-premium-bootstrap-4-admin/). You can find it in Tables -> Datatables.net and it has all the configurations that you need.

Hope it helps.

All the best,
Rares
