### ISSUE TITLE
Datatable

### ISSUE THREAD

**Issue by ashkan90** [creativetimofficial/black-dashboard#2]
Hi i want to edit your table to datatable but actually i don't know how can i do this. table doesn't be 
responsive when i add datatables.js to project 
![issue](https://user-images.githubusercontent.com/26023043/44982816-cbd15080-af7f-11e8-8927-1d145958d635.png)

**Comment by rarestoma** [comment]
Hi,

Thank you for the interest in our products. Can you please show me the code?

Best, 
Rares
