### ISSUE TITLE
Modal not working

### ISSUE THREAD

**Issue by marmarKamel** [creativetimofficial/black-dashboard#22]
hi,

i am trying to show modal in this template

https://themes.getbootstrap.com/product/black-dashboard-pro-premium-bootstrap-4-admin/

but it didn't work and also it didn't work in your live version or in your documentations

thanks

**Comment by rarestoma** [comment]
Hi @marmarKamel,

Thank you for working with our products.

Can you please tell me what browser and operating system are you using?

Thank you,
Rares
