### ISSUE TITLE
Navbar not working

### ISSUE THREAD

**Issue by ghost** [creativetimofficial/black-dashboard#23]
Hi,
I am using black dashboard PRO BootStrap 4. I am unable to get a standalone Navbar example going. 

I have imported the following files correctly into the HEAD tag of the HTML page:

```
<link href="assets/css/black-dashboard.css" rel="stylesheet" />
<script src="assets/js/core/jquery.min.js" type="text/javascript"></script>
<script src="assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="assets/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="assets/js/black-dashboard.min.js" type="text/javascript"></script>
```

This is the HTML code I am using:

```
<body>
    <nav class="navbar navbar-expand bg-warning">
        <div class="container">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown1"
                aria-controls="navbarNavDropdown1" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-bar navbar-kebab"></span>
                <span class="navbar-toggler-bar navbar-kebab"></span>
                <span class="navbar-toggler-bar navbar-kebab"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown1">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Pricing</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            Dropdown link
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</body>
```

What you will see is that at full page width the Navbar appears correctly. As soon as the browser window is decreased (beyond a responsive breakpoint md) the navbar completely disappears. I am not sure what I am doing wrong.

Please help.

Best Regards,

**Comment by rarestoma** [comment]
Hi @mhdjawwad,

Thank you for working with our products. 

Please try with this navbar code:

`
<nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent fixed-top bg-warning" style="top: 0px; transition: all 0.5s linear 0s;">
  <div class="container-fluid">
    <div class="navbar-wrapper">

      <a class="navbar-brand" href="javascript:void(0)">Navbar</a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-bar navbar-kebab"></span>
      <span class="navbar-toggler-bar navbar-kebab"></span>
      <span class="navbar-toggler-bar navbar-kebab"></span>
    </button>
    <div class="collapse navbar-collapse" id="navigation">
      <ul class="navbar-nav">
        <li class="nav-item ">
          <a href="register.html" class="nav-link">
            <i class="tim-icons icon-laptop"></i> Register
          </a>
        </li>
        <li class="nav-item ">
          <a href="login.html" class="nav-link">
            <i class="tim-icons icon-single-02"></i> Login
          </a>
        </li>
        <li class="nav-item  active ">
          <a href="pricing.html" class="nav-link">
            <i class="tim-icons icon-coins"></i> Pricing
          </a>
        </li>
        <li class="nav-item ">
          <a href="lock.html" class="nav-link">
            <i class="tim-icons icon-lock-circle"></i> Lock
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
`

I hope it helps.

All the best,
Rares

**Comment by ghost** [comment]
I did not try this but got a workaround going. I ended up designing the website navigation using bootstrap grid instead. This allowed me more control over the element placing.

Thanks,

**Comment by section117** [comment]
I am also having the same problem. The method @rarestoma mentioned doesn't seem to work. Could you please tell me a solution for it?

**Comment by rarestoma** [comment]
Hi @section117,

Thank you for working with our products.

Can you please give me more details about your issue?

Thank you,
Rares

**Comment by section117** [comment]
Hi @rarestoma
I think it's q problem with this version. If you take a look at the live previews of Black Dashboard and Black Dashboard Laravel Pro, in the upper left corner of web pages there's the name of that page (Ex - Dashboard, Icons..). But it's not visible in this (Black Dashboard Laravel).
And also the side bar completely disappears from this project while other two projects work fine. So I believe it's a problem with this template. I couldn't find a way to fix it. Could you please help me with this?

PS - You can validate above facts by looking at live previews of those 3 templates.

Thank you for replying

**Comment by section117** [comment]
![pro](https://user-images.githubusercontent.com/62211634/102846674-9b569e80-4436-11eb-958d-4c836437935f.JPG)
Black Dashboard Laravel Pro
![laravel](https://user-images.githubusercontent.com/62211634/102846703-b3c6b900-4436-11eb-8f61-bb42e03e6a4f.JPG)
Black Dashboard Laravel (Not working sidebar in mobile)
![black](https://user-images.githubusercontent.com/62211634/102846734-c7721f80-4436-11eb-8c7e-319d29866237.JPG)
Black Dashboard

@rarestoma I hope this explains the issue.

**Comment by rarestoma** [comment]
Hi @section117,

Can you please open this issue here (https://github.com/laravel-frontend-presets/black-dashboard/issues) so the team working on Laravel version can also see this and come with a solution?

Thank you,
Rares
