### ISSUE TITLE
Sidebar Toggle

### ISSUE THREAD

**Issue by qasimali000** [creativetimofficial/black-dashboard#26]
Hi

I'm trying to get toggle button on sidebar without media query, I want it there for whole time in every screen size but i'm unable to do it because there is a lots and lots of code there.

**Comment by rarestoma** [comment]
Hi @qasimali000,

Thank you for working with our products.

I took a look and yes, there a lot of changes that we need to take care of.  You have to add the navbar-toggle-bar bars style and sidebar's style also for > 991px and add a bigger margin-left to the navbar brand. I will add it as a suggestion for our next update.

Also, we provide a sidebar-mini in our PRO version (https://themes.getbootstrap.com/product/black-dashboard-pro-premium-bootstrap-4-admin/).

I hope it helps.

All the best,
Rares

**Comment by qasimali000** [comment]
Hi @rarestoma 

Thank you for your response.

If its okay with you, can you provide a clear code snippet so that I know that where these changes are to be made exactly. I'm looking forward to your response.

Regards
Qasim

**Comment by rarestoma** [comment]
Hi @qasimali000,

I made a new branch (feature/sidebar-toggle-whole-time) with those modifications. Please let me know if it works.

All the best,
Rares

**Comment by qasimali000** [comment]
It works.
Thanks
