### ISSUE TITLE
Need some help please

### ISSUE THREAD

**Issue by Cideg** [creativetimofficial/black-dashboard#4]
Hello and Hi :-), I think the tamplet is extremely good. Unfortunately, I can not use it myself 100%. Unfortunately, I get the user nciht out, no one can sign on or off. What else would have to be created to create profiles, delete, edit, etc ...
Is there somewhere for a video or a guide. Thank you for any help

Cideg

**Comment by rarestoma** [comment]
Hi Cideg,

Thank you for the interest in our products. We have the user profile page (https://demos.creative-tim.com/black-dashboard/examples/user.html) where you have an example of how a profile page should look. You can change the buttons so you can switch from the save button to edit, delete and so on. We will have more examples in the pro version that will be launched in a few days.

Please let me know if i can help you with anything else.

Best,
Rares
