### ISSUE TITLE
Error while using npm install

### ISSUE THREAD

**Issue by patrick-steve** [creativetimofficial/black-dashboard#40]
Got the following error while using npm install

`
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-scripts@4.0.1
npm ERR! Found: typescript@4.1.2
npm ERR! node_modules/typescript
npm ERR!   optional typescript@"4.1.2" from the root project        
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^3.2.1" from react-scripts@4.0.1  
npm ERR! node_modules/react-scripts
npm ERR!   react-scripts@"4.0.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: typescript@3.9.10
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"^3.2.1" from react-scripts@4.0.1
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"4.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\HUNGRYMINDS\AppData\Local\npm-cache\eresolve-report.txt for a full report.
`

**Comment by groovemen** [comment]
Hello @patrick-steve, 

Thank you for using our products and for letting us know about this issue. To solve it, we'll ask you to make the following changes: 

- you need to overwrite the `package.json` and `gulpfile.js` files with the ones attached below

[package.json.zip](https://github.com/creativetimofficial/black-dashboard/files/8752434/package.json.zip)
[gulpfile.js.zip](https://github.com/creativetimofficial/black-dashboard/files/8752435/gulpfile.js.zip)

Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by patrick-steve** [comment]
Hello Stefan (@groovemen ),

After making the above changes, the issue is solved. This information has been of great use to me, Thank you for your support!!
I have also created a pull request to make the necessary changes.

Yours truly,
Patrick
